import os
import streamlit as st
import pandas as pd
import plotly.express as px
from langgraph_agent import app, SupplyChainState, data_module, get_matching_suppliers
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail

# --- SendGrid Email Utility ---
def send_supplier_email(supplier_name, product_name, proposal_text):
    """Sends an automated RFQ/Outreach email via SendGrid with polished formatting."""
    sg_key = os.getenv("SENDGRID_API_KEY")
    from_email = os.getenv("SENDGRID_FROM_EMAIL")
    to_email = os.getenv("SENDGRID_TO_EMAIL") # Using user's provided 'to' email for PoC
    
    if not sg_key or not from_email:
        return False, "SendGrid credentials missing in .env"
    
    # 1. Parse the text: extract only the Executive Brief (before the divider)
    brief_content = proposal_text.split("---DEEP_ANALYSIS_DIVIDER---")[0].strip()
    
    # 2. Simple Markdown to HTML Conversion (Bolding and Line Breaks)
    # Handle bold marks (alternating <b> and </b>)
    parts = brief_content.split("**")
    html_body = parts[0]
    for i in range(1, len(parts)):
        tag = "<b>" if i % 2 != 0 else "</b>"
        html_body += tag + parts[i]
    if len(parts) % 2 == 0: html_body += "</b>"
    
    html_body = html_body.replace("\n", "<br>")

    subject = f"RFQ: Supply Chain Inquiry for {product_name} - {supplier_name}"
    
    # 3. Professional Email Template
    html_content = f"""
    <div style="font-family: Arial, sans-serif; color: #333; max-width: 650px; margin: 0 auto; border: 1px solid #e5e7eb; border-radius: 8px; overflow: hidden;">
        <div style="background-color: #6366f1; padding: 20px; color: white; text-align: center;">
            <h2 style="margin: 0; font-size: 20px;">Automated Procurement Request</h2>
        </div>
        <div style="padding: 30px; line-height: 1.6;">
            <p>Dear <strong>{supplier_name} Sourcing Team</strong>,</p>
            <p>Our autonomous procurement engine has identified a strategic requirement for the following item:</p>
            
            <div style="margin: 20px 0; padding: 15px; background-color: #f3f4f6; border-radius: 6px; text-align: center;">
                <span style="font-size: 18px; font-weight: bold; color: #111;">{product_name}</span>
            </div>

            <p><strong>Executive Procurement Brief:</strong></p>
            <div style="padding: 20px; border-left: 4px solid #6366f1; background-color: #f9fafb; margin: 15px 0;">
                {html_body}
            </div>

            <p>Please review these requirements and provide a formal quotation, including availability and confirmed lead time, at your earliest convenience.</p>
            
            <p style="margin-top: 30px;">Best Regards,<br>
            <strong>Autonomous Procurement Agent</strong><br>
            Inventory Intelligence Division</p>
        </div>
        <div style="background-color: #f9fafb; padding: 15px; text-align: center; font-size: 12px; color: #6b7280; border-top: 1px solid #e5e7eb;">
            This is an automated procurement inquiry generated by your AI Supplier Orchestration System.
        </div>
    </div>
    """
    
    message = Mail(
        from_email=from_email,
        to_emails=to_email,
        subject=subject,
        html_content=html_content
    )
    
    try:
        sg = SendGridAPIClient(sg_key)
        response = sg.send(message)
        if response.status_code in [200, 201, 202]:
            return True, f"Email successfully sent to {to_email}"
        else:
            return False, f"SendGrid error: Status Code {response.status_code}"
    except Exception as e:
        return False, f"Connection failed: {str(e)}"

# --- Page Config & Theme ---
st.set_page_config(
    page_title="Intelligent Supplier Replenishment &  Orchestration",
    page_icon="🛡️",
    layout="wide",
    initial_sidebar_state="collapsed"
)

@st.cache_resource
def get_cached_data_module():
    """Ensures the heavy supply chain datasets are loaded only once and shared across the session."""
    data_module.load_data()
    return data_module

# Initialize the optimized data layer
_dm = get_cached_data_module()

# --- Custom CSS for Premium Light Mode ---
st.html("""
    <style>
    /* Super-Resilient Premium Font Stack */
    @import url('https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;600;800&display=swap');
    
    html, body, [data-testid="stAppViewContainer"] {
        font-family: 'Plus Jakarta Sans', -apple-system, BlinkMacSystemFont, sans-serif;
        background-color: #f8fafc;
        color: #1e293b;
        width: 100% !important;
        overflow-x: hidden;
    }

    /* Remove Sidebar */
    [data-testid="stSidebar"] {
        display: none;
    }

    /* Glassmorphism Cards: Fluid & Safe */
    div[data-testid="stVerticalBlockBordered"] {
        background: rgba(255, 255, 255, 0.98) !important;
        backdrop-filter: blur(5px) !important;
        -webkit-backdrop-filter: blur(5px) !important;
        border: 1px solid #e2e8f0 !important;
        border-radius: 20px !important;
        padding: 1.5rem !important;
        margin-bottom: 1rem !important;
        box-shadow: 0 4px 12px rgba(0, 0, 0, 0.03) !important;
        transition: transform 0.3s ease !important;
    }
    
    div[data-testid="stVerticalBlockBordered"]:hover {
        transform: translateY(-2px);
        box-shadow: 0 10px 25px rgba(0, 0, 0, 0.05) !important;
    }

    /* Premium Headers */
    h1, h2, h3 {
        color: #0f172a !important;
        font-weight: 800 !important;
        letter-spacing: -0.04em !important;
    }
    
    .gradient-text {
        background: linear-gradient(135deg, #6366f1 0%, #a855f7 100%);
        -webkit-background-clip: text !important;
        -webkit-text-fill-color: transparent !important;
        font-weight: 800;
        font-size: clamp(1.8rem, 4vw, 3.5rem) !important;
        margin-bottom: 0.5rem;
    }

    /* Fluid Buttons */
    .stButton>button {
        background: linear-gradient(135deg, #6366f1 0%, #4f46e5 100%) !important;
        color: white !important;
        border: none !important;
        border-radius: 14px !important;
        padding: 0.6rem 2rem !important;
        font-weight: 700 !important;
        width: 100%;
        box-shadow: 0 4px 12px rgba(99, 102, 241, 0.2) !important;
    }
    
    /* Metrics */
    [data-testid="stMetricLabel"] {
        color: #64748b !important;
        font-weight: 650 !important;
        font-size: 0.75rem !important;
        text-transform: uppercase;
        letter-spacing: 0.05em;
    }
    [data-testid="stMetricValue"] {
        color: #4f46e5 !important;
        font-weight: 800 !important;
    }
    
    /* Clean Expanders */
    .stExpander {
        border: 1px solid #f1f5f9 !important;
        background: #ffffff !important;
        border-radius: 12px !important;
    }

    </style>
    """)

# --- Initialize Session State ---
if "agent_state" not in st.session_state or not isinstance(st.session_state.agent_state.get("forecasted_demand"), dict):
    initial_state = {
        "messages": [], "high_demand_products": None, "low_demand_products": None, "selected_product_ids": [], 
        "market_news": {}, "suppliers": {}, "selected_supplier_names": {}, "final_proposals": {},
        "match_types": {}, "mapped_categories": {}, "category_supplier_counts": {},
        "total_sku_count": 0, "market_growth": 0.0, "market_sentiment": "Stable", 
        "total_supplier_count": 0, "global_safety_score": 0.0, "global_discount_potential": 8.5,
        "forecasted_demand": {}, "inventory_impact": {}, "recommended_prices": {},
        "high_demand_count": 0, "low_demand_count": 0,
        "abc_distribution": {}, "inventory_status_counts": {},
        "methodology_guides": {
            "product_guide": "The AI analyzes a rolling **365-day historical sales window**, applying Prophet-level decomposition to extract core trends, seasonality multipliers, and residual demand volatility.",
            "supplier_guide": "The system dynamically maps internal product categories to a **Global Risk Database**, ranking vendors by a composite Risk Score (0-100) and negotiated discount potential."
        },
        "inventory_audit_summary": ""
    }
    st.session_state.agent_state = initial_state

state = st.session_state.agent_state

# Robustness: Ensure dictionaries are actually dictionaries (catches legacy scalar baggage)
for key in ["forecasted_demand", "inventory_impact", "recommended_prices", "market_news", "suppliers", "final_proposals"]:
    if not isinstance(state.get(key), dict):
        state[key] = {}
is_focused = bool(state.get("selected_product_ids"))
is_audited = state.get("high_demand_products") is not None
high_demand = state.get("high_demand_products")
low_demand = state.get("low_demand_products")

# Pre-compute labels for speed (prevents lambda lookup latency)
high_names = {}
low_names = {}
if high_demand is not None:
    high_names = dict(zip(high_demand['product_id'], high_demand['name']))
if low_demand is not None:
    low_names = dict(zip(low_demand['product_id'], low_demand['name']))


# --- Header Section ---
st.html('<h1 class="gradient-text">Intelligent Supplier Replenishment & Orchestration</h1>')
st.html('<div style="margin-top: 10px;"></div>')



if not is_audited and not is_focused:
    st.html('<div style="margin-top: 50px;"></div>')
    
    # --- Methodology Section (Initial Stage) ---
    with st.expander("Explore the Autonomous Intelligence Engine (How it Works)"):
        st.info("Our multi-layered analytical pipeline ensures procurement decisions are data-driven, risk-aware, and strategically optimized.")
        
        col_meth1, col_meth2 = st.columns(2)
        with col_meth1:
            with st.container(border=True):
                st.markdown("#### 📈 Demand Forecasting")
                st.write(state['methodology_guides']['product_guide'])
                st.caption("**Focus**: 365-Day Historical Trends, Seasonality, & Volatility Modeling.")

        with col_meth2:
            with st.container(border=True):
                st.markdown("#### 🛡️ Supplier & Risk Intelligence")
                st.write(state['methodology_guides']['supplier_guide'])
                st.caption("**Focus**: Global Risk Mapping, Dynamic Discounting, & Lead Time Adjusted Replenishment.")

    st.html('<div style="margin-top: 30px;"></div>')
    with st.container(border=True):
        st.markdown("### Demand Forecasting")
        st.write("The Procurement Agent is standing by to analyze your **50,000 SKU catalog**. Click the button below to trigger a full-catalog audit for replenishment and overstock priorities.")
        if st.button("Generate Insights", use_container_width=True, type="primary"):
            with st.spinner("AI forecasting 50,000 SKUs..."):
                st.session_state.agent_state = app.invoke(state)
                st.rerun()
    st.stop() # Halt execution here until audited

# --- Metrics Bar (Only visible if audited or focused) ---
# We will define columns here but populate them after determining the view
m1, m2, m3, m4, m5 = st.columns(5)

if is_focused:
    product_focus = None
    primary_id = state["selected_product_ids"][0]
    if high_demand is not None and primary_id in high_demand['product_id'].tolist():
        matches = high_demand[high_demand['product_id'] == primary_id]
        if not matches.empty:
            product_focus = matches.iloc[0]
    elif low_demand is not None and primary_id in low_demand['product_id'].tolist():
        matches = low_demand[low_demand['product_id'] == primary_id]
        if not matches.empty:
            product_focus = matches.iloc[0]
        
    if product_focus is not None:
        m1.metric("Primary Item Sales", f"{product_focus['quantity_sold']}", "Active Focus", delta_color="off")

    
    if state.get("suppliers") is not None:
        actual_count = state.get("category_supplier_count", len(state["suppliers"]))
        match_type = state.get("match_type", "Exact")
        
        if actual_count == 0:
            m2.metric("Available Suppliers", "0", "Sourcing Halted", delta_color="off")
        elif match_type in ["LLM", "Fuzzy"]:
            m2.metric("Alternative Suppliers", f"{actual_count}", "AI Semantic Match", delta_color="off")
        else:
            m2.metric("Product Suppliers", f"{actual_count}", "Exact Match", delta_color="off")
    else:
        m2.metric("Product Suppliers", "Searching...", "Supplier Match", delta_color="off")
        
    m3.metric("Market Interest", f"{state.get('market_growth', 0):.1f}%", state.get("market_sentiment", "Stable"))
    
    # Focused Safety & Discount
    item_safety = state.get("global_safety_score", 0.0) # For focused this should be item specific but using state for now
    item_discount = state.get("global_discount_potential", 0.0) 
    m4.metric("Item Safety", f"{item_safety:.1f}%", "Supplier Risk", delta_color="off")
    m5.metric("Discount Potential", f"{item_discount:.1f}%", "Negotiation Target", delta_color="off")
else:
    # Placeholder for global metrics which will be filled below
    pass


# --- Dynamic Metrics from Agent State ---
reliability = state.get("global_safety_score", 0.0)
# --- AI Insight Strip (Focused View) ---
if is_focused:
    st.html('<div style="margin-top: 25px;"></div>')
    i1, i2, i3 = st.columns(3)
    with i1:
        with st.container(border=True):
            f_demand_dict = state.get('forecasted_demand', {})
            total_f_demand = sum(f_demand_dict.values()) if isinstance(f_demand_dict, dict) else float(f_demand_dict)
            st.metric(
                "Forecasted 30-Day Demand", 
                f"{total_f_demand:,.0f} Units", 
                "Predictive Intelligence",
                help="Predictive demand for the next 30 days based on historical sales volume, seasonality trends, and market volatility."
            )

    with i2:
        with st.container(border=True):
            impact_dict = state.get('inventory_impact', {})
            total_impact = sum(impact_dict.values()) if isinstance(impact_dict, dict) else float(impact_dict)
            st.metric(
                "Inventory Optimization Impact", 
                f"${total_impact:,.2f}", 
                "Projected Loss Avoidance", 
                delta_color="off",
                help="Estimated financial risk of not taking action. Reflects either potential lost revenue (Stockout Risk) or unnecessary storage costs (Overstock Risk)."
            )
    with i3:
        with st.container(border=True):
            price_dict = state.get('recommended_prices', {})
            avg_price = (sum(price_dict.values()) / len(price_dict)) if isinstance(price_dict, dict) and price_dict else 0.0
            st.metric(
                "Avg Recommended Price", 
                f"${avg_price:,.2f}", 
                "Dynamic Strategy Engaged",
                help="AI-suggested mean unit price optimized for throughput across selected SKUs."
            )

    # Clarity Enhancement: Detailed Methodology Explainer
    with st.expander("AI Analysis Methodology - How these numbers are calculated"):
        st.markdown(f"""
        ### Understanding AI Insights
        
        **1. Forecasted 30-Day Demand ({total_f_demand:,.0f} Units)**
        This isn't just a simple average. Our ML model analyzes the last 365 days of sales for **{product_focus['name']}** and other selected SKUs, applies the respective **seasonality multipliers**, and adjusts for market volatility. It predicts exactly how many units you will likely sell in the next 30 days.
        
        **2. Inventory Optimization Impact (${total_impact:,.2f})**
        This represents the **financial risk** of the current situation. 
        - If stock is low: This is the **Stockout Risk** (the revenue you'll lose if you don't restock now).
        - If stock is high: This is the **Holding Cost** (the money tied up in storage for items that won't sell this month).
        
        **3. Recommended Optimized Price (${avg_price:,.2f} Avg)**
        The AI evaluates **Inventory Turnover** (how fast it sells) vs **Volatility** (how stable the demand is). 
        - High stability + High speed = The AI suggests a slight premium to maximize margin.
        - Low stability + Low speed = The AI suggests a strategic discount to clear warehouse space.
        """)

# --- Main Dashboard Control Flow ---
if not is_focused:
    is_high_view = (st.session_state.get("global_view_toggle") != "Slow-Moving Inventory (Overstock Risk)")

    # 1. Product Selection & Analysis Area
    st.markdown("### Product Selection & Analysis")
    with st.container(border=True):
        # Determine dataset based on strategy toggle
        if is_high_view:
            options_list = high_demand['product_id'].tolist() if high_demand is not None else []
            format_dict = high_names
            count = state.get('high_demand_count', 0)
            label_text = "High-Demand"
            button_text = "Analyze Procurement"
            spinner_text = "researching supply chain"
        else:
            options_list = low_demand['product_id'].tolist() if low_demand is not None else []
            format_dict = low_names
            count = state.get('low_demand_count', 0)
            label_text = "Slow-Moving"
            button_text = "Analyze Liquidation"
            spinner_text = "auditing overstock risk"
            
        st.caption(f"Analyze specific SKU from **{count:,}** {label_text} items")
        c_sel, c_btn = st.columns([3, 1])
        with c_sel:
            selected_skus = st.multiselect(
                f"Select {label_text} SKUs (Max 3)",
                options=options_list,
                format_func=lambda x: f"{format_dict.get(x, 'Unknown')} ({x})",
                key="sku_sel_top",
                max_selections=3,
                label_visibility="collapsed"
            )
        with c_btn:
            if st.button(button_text, use_container_width=True, key="btn_analyze_top", type="primary"):
                if not selected_skus:
                    st.warning("Please select at least 1 SKU.")
                    st.stop()
                state["selected_product_ids"] = selected_skus
                state["suppliers"] = {}
                state["selected_supplier_names"] = {}
                with st.spinner(f"Agent {spinner_text} for {len(selected_skus)} items..."):
                    st.session_state.agent_state = app.invoke(state)
                    st.rerun()
    st.html('<div style="margin-top: 30px;"></div>')
    
    st.markdown("### Risk & Market Analysis")
    
    # 🤖 Agent Audit Report Summary
    audit_summary = state.get("inventory_audit_summary", "Agent is performing an autonomous catalog audit...")
    with st.container(border=True):
        st.markdown("#### Audit Summary")
        st.write(audit_summary)

    st.html('<div style="margin-top: 25px;"></div>')
    
    # Inventory View Selection (Radio for reactivity)
    inv_view = st.radio(
        "Inventory Strategy Focus",
        options=["High Demand Products", "Slow-Moving Inventory (Overstock Risk)"],
        horizontal=True,
        label_visibility="collapsed",
        key="global_view_toggle"
    )
    is_high_view = (inv_view == "High Demand Products")

    # Populate Metrics Bar for Global View
    if is_high_view:
        m1.metric("Items in Demand", f"{state.get('high_demand_count', 0):,}", "High Demand List", delta_color="off")
    else:
        m1.metric("Slow-Moving Items", f"{state.get('low_demand_count', 0):,}", "Overstock Risk", delta_color="normal")
        
    m2.metric("Suppliers Monitored", f"{state.get('total_supplier_count', 0):,}", "Global Network", delta_color="off")
    m3.metric("Average Market Growth", f"{state.get('market_growth', 0):.1f}%", state.get("market_sentiment", "Stable"))
    
    reliability = state.get("global_safety_score", 0.0)
    discount_pot = state.get("global_discount_potential", 0.0)
    m4.metric("Supplier Safety", f"{reliability:.1f}%", "Weighted Avg", delta_color="off")
    m5.metric("Discount Potential", f"{discount_pot:.1f}%", "Market Avg", delta_color="off")

    st.html('<div style="margin-top: 20px;"></div>')
    
    
    if is_high_view:
        st.markdown(f"#### Strategic Inventory Data: High Demand ({state.get('high_demand_count', 0):,})")
        st.dataframe(high_demand[['product_id', 'name', 'category', 'quantity_sold']], use_container_width=True, hide_index=True)
    else:
        st.markdown(f"#### Strategic Inventory Data: Overstock Risk ({state.get('low_demand_count', 0):,})")
        st.dataframe(low_demand[['product_id', 'name', 'category', 'quantity_sold']], use_container_width=True, hide_index=True)

else:
    # Navigation Return Button for Focused View
    if st.button("⬅️ Return to Global Market Overview"):
        state["selected_product_ids"] = []
        state["suppliers"] = {}
        state["market_news"] = {}
        state["final_proposals"] = {}
        state["selected_supplier_names"] = {}
        st.session_state.agent_state = state
        st.rerun()

    selected_ids = state.get("selected_product_ids", [])
    if not selected_ids:
        st.error("⚠️ No products selected.")
        if st.button("Return to Global View"):
            state["selected_product_ids"] = []
            st.rerun()
        st.stop()

    # Group selected products to generate dynamic tab headers
    valid_products = []
    tab_names = []
    
    for pid in selected_ids:
        # Resolve current product row
        curr_prod = None
        if high_demand is not None and pid in high_demand['product_id'].tolist():
            matches = high_demand[high_demand['product_id'] == pid]
            curr_prod = matches.iloc[0] if not matches.empty else None
        elif low_demand is not None and pid in low_demand['product_id'].tolist():
            matches = low_demand[low_demand['product_id'] == pid]
            curr_prod = matches.iloc[0] if not matches.empty else None
            
        if curr_prod is not None:
            valid_products.append((pid, curr_prod))
            tab_names.append(f"📦 {curr_prod['name']}")
        else:
            st.warning(f"⚠️ Selected product '{pid}' is no longer actively monitored.")
            
    if not valid_products:
        st.stop()
        
    st.html('<div style="margin-top: 20px;"></div>')
    
    # Render Streamlit Multi-Tabs
    tabs = st.tabs(tab_names)
    
    # Iterate dynamically through tabs and embed timeline inside
    for tab, (pid, curr_prod) in zip(tabs, valid_products):
        with tab:
            st.markdown(f"### AI Insights for Product and Supplier")
            
            # Timeline/Log View
            with st.container(border=True):
                st.subheader("Intelligence Research Feed")
                
                # Step 1: Demand
                with st.chat_message("assistant", avatar="🔍"):
                    st.write(f"**Inventory Audit**")
                    demand_type = "high" if pid in (high_demand['product_id'].tolist() if high_demand is not None else []) else "low"
                    st.write(f"During my audit of the 50k catalog, I flagged **{curr_prod['name']}** as a **{demand_type}-priority** item.")
                    
                    f_demand = state.get('forecasted_demand', {}).get(pid, 0.0)
                    i_impact = state.get('inventory_impact', {}).get(pid, 0.0)
                    
                    st.write(f"📈 **Demand Forecast:** Predicting **{f_demand:,.0f} units** over 30 days ({curr_prod['seasonality_factor']}x seasonality).")
                    st.write(f"💰 **Financial Risk:** Failure to act presents a **${i_impact:,.2f}** inventory imbalance risk.")
    
                # Step 2: Market Signals
                with st.chat_message("assistant", avatar="🌍"):
                    st.write("**External Market Signals**")
                    news_data = state.get("market_news", {}).get(pid, {})
                    
                    if isinstance(news_data, dict) and news_data.get("status") == "success":
                        news = news_data.get("results", [])
                        summary = news_data.get("summary", "")
                        if news:
                            st.info(f"**Agent Intelligence Summary:** {summary}")
                            with st.expander(f"View {len(news)} Market Signal Sources"):
                                for item in news:
                                    st.markdown(f"> **{item['title']}** ([Source]({item['link']}))")
                        else:
                            st.warning("No disruptive external signals detected in current cycle. Market appears stable.")
                    elif isinstance(news_data, dict) and news_data.get("status") == "error":
                        st.error(f"⚠️ Agent News Sensors Offline: {news_data.get('message')}")
                    else:
                        st.warning("Market sensors pending or returned unexpected response.")
    
                # Step 3: Supplier Intelligence
                with st.chat_message("assistant", avatar="🛡️"):
                    st.write("**Supplier Intelligence & Selection**")
                    suppliers = state.get("suppliers", {}).get(pid)
                    
                    if suppliers is not None:
                        if suppliers.empty:
                            st.error(f"⚠️ No supplier match found for **{curr_prod['category']}**.")
                        else:
                            match_type = state.get("match_types", {}).get(pid, "Exact")
                            mapped_cat = state.get("mapped_categories", {}).get(pid, curr_prod['category'])
                            
                            if match_type == "Exact":
                                st.write(f"The AI has identified the **Top {len(suppliers)} Suppliers** from the global network for the **{curr_prod['category']}** category.")
                            else:
                                st.info(f"**AI Semantic Bridge:** The strict category '{curr_prod['category']}' was mapped dynamically to: **'{mapped_cat}'**.")
                                st.write(f"I have identified the **Top {len(suppliers)} Alternative Suppliers** capable of sourcing this product based on Risk and Price.")
                            
                            st.dataframe(
                                suppliers[['Supplier Name', 'Location', 'Risk Score', 'Final Price', 'Discount %', 'Current Stock Levels', 'Shipment ETA', 'Recommendation']], 
                                use_container_width=True,
                                hide_index=True,
                                key=f"df_{pid}"
                            )
                            
                            with st.expander("Supplier Selection Methodology - How we rank these vendors"):
                                st.markdown("""
                                ### How our AI evaluates Suppliers
                                **1. Risk Score**: Geopolitical, Logistics, Economic Volatility. (0 = Safest, 100 = High Risk).
                                **2. Final Price Calculation**: Base price applying a Dynamic Discount negotiated based on relative Cost Competitiveness.
                                **3. Shipment ETA**: Adjusted ETA calculation inclusive of historical Delay Days.
                                **4. Recommendation Hierarchy**:
                                - ⭐ Best Overall (Low Risk)
                                - 💰 Best Price
                                """)
    
                            selected_supp_names = st.multiselect(
                                f"Select Suppliers for {curr_prod['name']} to proceed with Outreach:",
                                options=suppliers['Supplier Name'].tolist(),
                                default=[suppliers['Supplier Name'].tolist()[0]] if not suppliers.empty else None,
                                help="The AI has automatically pre-selected the 'Best Overall' based on lowest risk.",
                                key=f"supp_sel_{pid}"
                            )
                            
                            if st.button(f"Auto-Send Email for {curr_prod['name']}", type="primary", use_container_width=True, key=f"btn_email_{pid}"):
                                # Execute actual backend mail dispatch
                                base_proposal = state.get("final_proposals", {}).get(pid)
                                if not base_proposal:
                                    st.warning(f"⚠️ **Context Missing:** Please click 'Synthesize Final Strategic Memo' below first to generate the AI procurement justification before emailing suppliers.")
                                    st.stop()
                                
                                results = []
                                for s_name in selected_supp_names:
                                    success, msg = send_supplier_email(s_name, curr_prod['name'], base_proposal)
                                    results.append((s_name, success, msg))
                                
                                # UI Feedback
                                failures = [r for r in results if not r[1]]
                                if not failures:
                                    st.toast(f"Autonomous email successfully dispatched to {len(selected_supp_names)} suppliers!", icon="✉️")
                                    st.success(f"**Outreach complete.** Automated RFQ emails seamlessly formatted and transmitted via SendGrid to: {', '.join(selected_supp_names)}")
                                else:
                                    for s_name, success, msg in failures:
                                        st.error(f"Failed to send email to {s_name}: {msg}")
    
                # Step 4: Final Recommendation
                final_proposal = state.get("final_proposals", {}).get(pid)
                if not final_proposal:
                    if suppliers is not None and not suppliers.empty:
                        if st.button(f"⚡ Synthesize Final Strategic Memo for {curr_prod['name']}", key=f"btn_synth_{pid}"):
                            with st.status("Agent synthesizing final recommendation...", expanded=True) as status:
                                if "selected_supplier_names" not in state:
                                    state["selected_supplier_names"] = {}
                                state["selected_supplier_names"][pid] = selected_supp_names
                                
                                st.session_state.agent_state = app.invoke(state)
                                status.update(label="Synthesis Complete", state="complete", expanded=False)
                                st.rerun()
                else:
                    with st.chat_message("assistant", avatar="📄"):
                        st.write("**Executive Procurement Proposal**")
                        if "---DEEP_ANALYSIS_DIVIDER---" in final_proposal:
                            parts = final_proposal.split("---DEEP_ANALYSIS_DIVIDER---")
                            st.info(parts[0].strip())
                            with st.expander("View Detailed Strategic Report"):
                                st.markdown(parts[1].strip())
                        else:
                            st.markdown(final_proposal)
    
            st.html('<div style="margin-top: 40px;"></div>')

# --- Global Footer ---
st.html('<div style="margin-top: 60px;"></div>')
st.markdown("---")
_, col_footer, _ = st.columns([4, 1, 4])
with col_footer:
    if st.button("🔄 Reset", key="btn_reset_global_bottom", use_container_width=True):
        st.session_state.clear()
        st.rerun()
